In [9]:
import calml
import dummy

In [6]:
df = calml.get_hour_features('2014-01-01 00:00:00', '2018-03-15 00:00:00')

In [14]:
dummies = dummy.Dummies()
dummies.fit(df, ['year', 'season', 'month', 'monthday', 'weekday', 'hour'])
dm_df = dummies.replace(df)
dm_df.head()

,holiday,year_2014,year_2015,year_2016,year_2017,year_2018,season_1,season_2,season_3,season_4,...,hour_21,hour_22,hour_23,weekday_0,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,weekday_6
datetime,,,,,,,,,,,,,,,,,,,,,
2014-01-01 00:00:00,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2014-01-01 01:00:00,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2014-01-01 02:00:00,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2014-01-01 03:00:00,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2014-01-01 04:00:00,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [15]:
dm_df.to_csv('data/calendar.csv')